name: Fabric Deployment Pipeline
'on':
  workflow_dispatch: {}
jobs:
  deploy-dev-to-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check available scripts
      shell: pwsh
      run: Get-ChildItem -Recurse
    - name: "Ejecutar despliegue Dev \u2192 Test"
      shell: pwsh
      run: ./scripts/DevToTest.ps1 -ClientId "${{ secrets.CLIENT_ID
        }}" -TenantId "${{ secrets.TENANT_ID }}" -ClientSecret "${{ secrets.CLIENT_SECRET
        }}"
  deploy-test-to-prod:
    runs-on: windows-latest
    needs:
    - deploy-dev-to-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Check available scripts
      shell: pwsh
      run: Get-ChildItem -Recurse
    - name: "Ejecutar despliegue Test \u2192 Prod"
      shell: pwsh
      run: ./scripts/TestToProd.ps1 -ClientId "${{ secrets.CLIENT_ID }}"
        -TenantId "${{ secrets.TENANT_ID }}" -ClientSecret "${{ secrets.CLIENT_SECRET
        }}"
    - name: "Confirmar \xE9xito del despliegue"
      shell: pwsh
      run: "Write-Host '\u2705 Despliegue Test \u2192 Prod completado exitosamente.'\\ -ForegroundColor Green"
    - name: Send alert to Teams
      uses: Ilshidur/action-discord@master
      with:
        webhook: ${{ secrets.TEAMS_WEBHOOK }}
        message: "\u2705 Despliegue Test \u2192 Prod completado exitosamente en GitHub\\ Actions."
