
name: Deploy to Microsoft Fabric
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cargar variables de entorno
        run: export $(grep -v '^#' .env | xargs)
      - name: Ejecutar script de despliegue
        run: pwsh scripts/DeployDevToTest_final_corregido.ps1
