name: Deploy to Microsoft Fabric

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Ejecutar despliegue Dev → Test
        shell: pwsh
        run: ./scripts/DeployDevToTest_final_corregido.ps1

      - name: Ejecutar despliegue Test → Prod
        shell: pwsh
        run: ./scripts/DeployTestToProd_corregido.ps1
