name: Fabric Deployment Pipeline
'on':
  workflow_dispatch: {}
jobs:
  deploy-dev-to-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Dev to Test Deployment
      shell: pwsh
      run: ./DeployDevToTest_final_validado_stages.ps1
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  deploy-test-to-prod:
    runs-on: windows-latest
    needs:
    - deploy-dev-to-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run Test to Prod Deployment
      shell: pwsh
      run: ./DeployTestToProd_corregido_validado_stages.ps1
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        TENANT_ID: ${{ secrets.TENANT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
