name: Deploy Lakehouse to Test

on:
  push:
    branches:
      - main
    paths:
      - 'fabric/dev/lakehouses/**'  # Detecta cambios en cualquier archivo dentro del Lakehouse

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lakehouse:
          - name: lakehouse1
          - name: lakehouse2
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Detect Lakehouse changes
        id: changes
        run: |
          echo "Detectando cambios en Lakehouse..."
          # Aquí podrías agregar lógica para comparar nombres o metadatos si los tenés versionados

      - name: Deploy to Test
        if: steps.changes.outputs.modified == 'true'
        run: |
          echo "Desplegando Lakehouse ${{ matrix.lakehouse.name }} a Test..."
          # Aquí iría tu comando de despliegue, por ejemplo usando Fabric CLI o API
