- name: Deploy to Test Workspace
  if: success()  # Solo se ejecuta si los pasos anteriores fueron exitosos
  env:
    FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
  run: |
    echo "Desplegando desde Dev a Test..."
    curl -X POST "https://api.fabric.microsoft.com/pipelines/github-integration-pipelines/deploy" \
      -H "Authorization: Bearer $FABRIC_TOKEN" \
      -H "Content-Type: application/json" \
      -d '{
            "sourceWorkspaceId": "WS-github-integration-dev",
            "targetWorkspaceId": "ws-github... (Test)"
          }'
