name: Deploy to Fabric Test

on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy artifacts from Dev to Test
        env:
          FABRIC_API_TOKEN: ${{ secrets.FABRIC_API_TOKEN }}
          PIPELINE_ID: ${{ secrets.FABRIC_PIPELINE_ID }}
        run: |
          curl -X POST https://api.fabric.microsoft.com/deployment/pipelines/${PIPELINE_ID}/promote \
            -H "Authorization: Bearer $FABRIC_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "sourceStage": "dev",
              "targetStage": "test",
              "artifacts": [
                { "name": "LakehouseA", "type": "Lakehouse" },
                { "name": "NotebookB", "type": "Notebook" }
              ]
            }'
