name: Deploy Microsoft Fabric Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # Cambiar según la versión que utilices

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Test project
      run: dotnet test --no-build --verbosity normal

    - name: Deploy to Test environment
      env:
        FABRIC_WORKSPACE: test
        AUTH_TOKEN: ${{ secrets.FABRIC_AUTH_TOKEN }}
      run: |
        echo "Deploying to Test environment"
        # Aquí iría el comando o script para realizar el despliegue a Test

    - name: Deploy to Production environment
      if: success()
      env:
        FABRIC_WORKSPACE: prod
        AUTH_TOKEN: ${{ secrets.FABRIC_AUTH_TOKEN }}
      run: |
        echo "Deploying to Production environment"
        # Aquí iría el comando o script para realizar el despliegue a Prod
