name: Deploy Azure ML Pipeline to Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy pipeline to Test
        run: |
          az ml pipeline-endpoint invoke \
            --name VHS-github-integration-test \
            --endpoint-type batch \
            --workspace-name your-workspace-name \
            --resource-group your-resource-group \
            --experiment-name your-experiment-name \
            --set-parameters pipeline_version=6
