- name: Get Workspaces
  env:
    FABRIC_TOKEN: ${{ secrets.FABRIC_TOKEN }}
  run: |
    WORKSPACE_RESPONSE=$(curl -s -X GET \
      "https://api.fabric.microsoft.com/v1/workspaces" \
      -H "Authorization: Bearer $FABRIC_TOKEN" \
      -H "Content-Type: application/json")

    echo "Workspace API response:"
    echo "$WORKSPACE_RESPONSE" | jq .
