name: Deploy Dev to Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PowerShell Az module
        run: Install-Module -Name Az -Force -Scope CurrentUser
        shell: pwsh

      - name: Run Fabric Deployment Script
        run: ./DeployAll.ps1
        shell: pwsh
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          SECRET_VALUE: ${{ secrets.SECRET_VALUE }}
