
name: Microsoft Fabric CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  FABRIC_API_URL: "https://api.fabric.microsoft.com/v1"
  AZURE_LOGIN_URL: "https://login.microsoftonline.com"
  WORKSPACE_NAME: "WS-github-integration-dev"
  PIPELINE_NAME: "github-integration-pipelines"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Azure AD Token
        id: get_token
        run: |
          TOKEN_RESPONSE=$(curl -s -X POST             "${{ env.AZURE_LOGIN_URL }}/${{ secrets.TENANT_ID }}/oauth2/v2.0/token"             -H "Content-Type: application/x-www-form-urlencoded"             -d "client_id=${{ secrets.CLIENT_ID }}"             -d "client_secret=${{ secrets.CLIENT_SECRET }}"             -d "scope=https://api.fabric.microsoft.com/.default"             -d "grant_type=client_credentials")
          echo "Raw token response:"
          echo "$TOKEN_RESPONSE"
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          echo "::add-mask::$ACCESS_TOKEN"
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Debug Access Token
        run: |
          echo "Access token output:"
          echo "${{ steps.get_token.outputs.access_token }}"
