name: Microsoft Fabric CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FABRIC_API_URL: "https://api.fabric.microsoft.com/v1"  # URL base correcta
  AZURE_LOGIN_URL: "https://login.microsoftonline.com"

jobs:
  get-token-and-workspace:
    name: Get Azure AD Token and Workspace ID
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.get_token.outputs.access_token }}
      workspace_id: ${{ steps.get_workspace.outputs.workspace_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Azure AD Token
        id: get_token
        run: |
          TOKEN_RESPONSE=$(curl -s -X POST \
            "${{ env.AZURE_LOGIN_URL }}/${{ secrets.TENANT_ID }}/oauth2/v2.0/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.CLIENT_ID }}" \
            -d "client_secret=${{ secrets.CLIENT_SECRET }}" \
            -d "scope=https://api.fabric.microsoft.com/.default" \
            -d "grant_type=client_credentials")
          
          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          
          if [ -z "$ACCESS_TOKEN" ] || [ "$ACCESS_TOKEN" == "null" ]; then
            echo "Error obteniendo token" >&2
            exit 1
          fi

          echo "::add-mask::$ACCESS_TOKEN"
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_OUTPUT

      - name: Get Workspace ID
        id: get_workspace
        run: |
          WORKSPACE_RESPONSE=$(curl -s -X GET \
            "${{ env.FABRIC_API_URL }}/workspaces" \
            -H "Authorization: Bearer ${{ steps.get_token.outputs.access_token }}" \
            -H "Content-Type: application/json")

          WORKSPACE_ID=$(echo "$WORKSPACE_RESPONSE" | jq -r --arg name "${{ vars.WORKSPACE_NAME }}" '.value[] | select(.displayName == $name) | .id')
          
          if [ -z "$WORKSPACE_ID" ]; then
            echo "Workspace no encontrado" >&2
            exit 1
          fi
          
          echo "workspace_id=$WORKSPACE_ID" >> $GITHUB_OUTPUT
          echo "Found workspace: $WORKSPACE_ID"

  deploy-dev-to-test:
    name: Deploy from Dev to Test
    needs: get-token-and-workspace
    runs-on: ubuntu-latest
    steps:
      - name: Deploy content
        run: |
          echo "Starting deployment from Dev to Test workspace..."

          # Obtener el token del output del job anterior
          ACCESS_TOKEN="${{ needs.get-token-and-workspace.outputs.access_token }}"
          DEV_WORKSPACE_ID="${{ secrets.DEV_WORKSPACE_ID }}"
          TEST_WORKSPACE_ID="${{ secrets.TEST_WORKSPACE_ID }}"

          # Verificar que el token no esté vacío
          if [ -z "$ACCESS_TOKEN" ]; then
            echo "Error: Token de acceso vacío" >&2
            exit 1
          fi

          # Mostrar el token (opcional para depuración)
          echo "Token de acceso: $ACCESS_TOKEN"

          # Construir payload JSON
          JSON_PAYLOAD=$(jq -n --arg target "$TEST_WORKSPACE_ID" '{targetWorkspaceId: $target}')

          # Endpoint para despliegue, usando la variable de entorno
          DEPLOY_ENDPOINT="${{ env.FABRIC_API_URL }}/workspaces/$DEV_WORKSPACE_ID/deployWorkspace"

          # Ejecutar despliegue
          DEPLOY_RESPONSE=$(curl -s -X POST "$DEPLOY_ENDPOINT" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$JSON_PAYLOAD")

          echo "Deployment initiated"
          echo "$DEPLOY_RESPONSE"

  deploy-test-to-prod:
    name: Deploy from Test to Prod
    needs: deploy-dev-to-test
    runs-on: ubuntu-latest
    steps:
      - name: Copy content from Test to Prod
        run: |
          echo "Starting deployment from Test to Prod workspace..."

          # Obtener el token del output del job anterior
          ACCESS_TOKEN="${{ needs.get-token-and-workspace.outputs.access_token }}"
          TEST_WORKSPACE_ID="${{ secrets.TEST_WORKSPACE_ID }}"
          PROD_WORKSPACE_ID="${{ secrets.PROD_WORKSPACE_ID }}"

          # Verificar que el token no esté vacío
          if [ -z "$ACCESS_TOKEN" ];
