
name: Microsoft Fabric CI/CD and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FABRIC_API_URL: "https://api.fabric.microsoft.com/v1"
  AZURE_LOGIN_URL: "https://login.microsoftonline.com"

jobs:
  deploy-dev-to-test:
    name: Get Token, Workspace ID and Deploy Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Azure AD Token
        id: get_token
        run: |
          TOKEN_RESPONSE=$(curl -s -X POST             "${{ env.AZURE_LOGIN_URL }}/${{ secrets.TENANT_ID }}/oauth2/v2.0/token"             -H "Content-Type: application/x-www-form-urlencoded"             -d "client_id=${{ secrets.CLIENT_ID }}"             -d "client_secret=${{ secrets.CLIENT_SECRET }}"             -d "scope=https://api.fabric.microsoft.com/.default"             -d "grant_type=client_credentials")

          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.access_token')
          echo "::add-mask::$ACCESS_TOKEN"
          echo "access_token=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Get Workspace ID
        id: get_workspace
        run: |
          WORKSPACE_RESPONSE=$(curl -s -X GET             "${{ env.FABRIC_API_URL }}/workspaces"             -H "Authorization: Bearer ${{ env.access_token }}"             -H "Content-Type: application/json")

          DEV_WORKSPACE_ID=$(echo "$WORKSPACE_RESPONSE" | jq -r --arg name "${{ vars.DEV_WORKSPACE_NAME }}" '.value[] | select(.displayName == $name) | .id')
          TEST_WORKSPACE_ID=$(echo "$WORKSPACE_RESPONSE" | jq -r --arg name "${{ vars.TEST_WORKSPACE_NAME }}" '.value[] | select(.displayName == $name) | .id')

          echo "dev_workspace_id=$DEV_WORKSPACE_ID" >> $GITHUB_ENV
          echo "test_workspace_id=$TEST_WORKSPACE_ID" >> $GITHUB_ENV

          echo "Found Dev workspace: $DEV_WORKSPACE_ID"
          echo "Found Test workspace: $TEST_WORKSPACE_ID"

      - name: Copy artifacts from Dev to Test
        run: |
          RESPONSE=$(curl -s -X POST             "$FABRIC_API_URL/workspaces/$TEST_WORKSPACE_ID/importAllArtifacts?sourceWorkspaceId=$DEV_WORKSPACE_ID"             -H "Authorization: Bearer $ACCESS_TOKEN"             -H "Content-Type: application/json")

          echo "API response: $RESPONSE"

          STATUS=$(echo "$RESPONSE" | jq -r '.status')
          if [ "$STATUS" != "Succeeded" ]; then
            echo "❌ Error: Falló la copia de artefactos de Dev a Test."
            exit 1
          fi

          echo "✅ Artefactos copiados exitosamente de Dev a Test."
        env:
          FABRIC_API_URL: https://api.fabric.microsoft.com/v1
          ACCESS_TOKEN: ${{ env.access_token }}
          DEV_WORKSPACE_ID: ${{ env.dev_workspace_id }}
          TEST_WORKSPACE_ID: ${{ env.test_workspace_id }}
