name: Microsoft Fabric CI/CD and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FABRIC_API_URL: "https://api.fabric.microsoft.com/v1"

jobs:
  deploy-dev-test-prod:
    name: Deploy Artifacts Dev → Test → Prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate secrets
        run: |
          if [ -z "${{ secrets.ACCESS_TOKEN }}" ]; then
            echo "❌ Error: El token de acceso (ACCESS_TOKEN) no está definido."
            exit 1
          fi

          if [ -z "${{ secrets.DEV_WORKSPACE_ID }}" ] || [ -z "${{ secrets.TEST_WORKSPACE_ID }}" ] || [ -z "${{ secrets.PROD_WORKSPACE_ID }}" ]; then
            echo "❌ Error: Uno o más IDs de workspace (DEV, TEST, PROD) no están definidos."
            exit 1
          fi

          echo "✅ Validación de token y workspace IDs completada."

      - name: Validate and Copy artifacts from Dev to Test
        run: |
          RESPONSE=$(curl -s -X GET \
            "$FABRIC_API_URL/workspaces/${{ secrets.DEV_WORKSPACE_ID }}/getPendingChanges?targetWorkspaceId=${{ secrets.TEST_WORKSPACE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json")

          CHANGES=$(echo "$RESPONSE" | jq -r '.hasPendingChanges')
          if [ "$CHANGES" != "true" ]; then
            echo "ℹ️ No hay cambios pendientes entre Dev y Test."
            exit 0
          fi

          echo "✅ Cambios pendientes detectados entre Dev y Test. Ejecutando copia..."

          RESPONSE=$(curl -s -X POST \
            "$FABRIC_API_URL/workspaces/${{ secrets.TEST_WORKSPACE_ID }}/importAllArtifacts?sourceWorkspaceId=${{ secrets.DEV_WORKSPACE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}')

          echo "API response: $RESPONSE"

          STATUS=$(echo "$RESPONSE" | jq -r '.status')
          if [ "$STATUS" != "Succeeded" ]; then
            echo "❌ Error: Falló la copia de artefactos de Dev a Test."
            exit 1
          fi

          echo "✅ Artefactos copiados exitosamente de Dev a Test."

      - name: Validate and Copy artifacts from Test to Prod
        run: |
          RESPONSE=$(curl -s -X GET \
            "$FABRIC_API_URL/workspaces/${{ secrets.TEST_WORKSPACE_ID }}/getPendingChanges?targetWorkspaceId=${{ secrets.PROD_WORKSPACE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json")

          CHANGES=$(echo "$RESPONSE" | jq -r '.hasPendingChanges')
          if [ "$CHANGES" != "true" ]; then
            echo "ℹ️ No hay cambios pendientes entre Test y Prod."
            exit 0
          fi

          echo "✅ Cambios pendientes detectados entre Test y Prod. Ejecutando copia..."

          RESPONSE=$(curl -s -X POST \
            "$FABRIC_API_URL/workspaces/${{ secrets.PROD_WORKSPACE_ID }}/importAllArtifacts?sourceWorkspaceId=${{ secrets.TEST_WORKSPACE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{}')

          echo "API response: $RESPONSE"

          STATUS=$(echo "$RESPONSE" | jq -r '.status')
          if [ "$STATUS" != "Succeeded" ]; then
            echo "❌ Error: Falló la copia de artefactos de Test a Prod."
            exit 1
          fi
          echo "✅ Artefactos copiados exitosamente de Test a Prod."
