name: Fabric Deployment Workflow
true:
  push:
    branches:
    - main
jobs:
  get-token:
    name: Obtener token de Azure AD
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.get_token.outputs.access_token }}
    steps:
    - name: Obtener token con client_credentials
      id: get_token
      run: "response=$(curl -X POST https://login.microsoftonline.com/${{ secrets.TENANT_ID\
        \ }}/oauth2/v2.0/token \\\n  -H \"Content-Type: application/x-www-form-urlencoded\"\
        \ \\\n  -d \"client_id=${{ secrets.CLIENT_ID }}&scope=https%3A%2F%2Fapi.fabric.microsoft.com%2F.default&client_secret=${{\
        \ secrets.CLIENT_SECRET }}&grant_type=client_credentials\")\necho \"access_token=$(echo\
        \ $response | jq -r .access_token)\" >> $GITHUB_OUTPUT\n"
  sync-from-github:
    name: Sincronizar contenido desde GitHub a Dev
    runs-on: ubuntu-latest
    needs: get-token
    steps:
    - name: Llamar a la API de Fabric para sincronizar contenido
      run: "curl -X POST https://api.fabric.microsoft.com/v1/workspaces/3852a0cf-16cb-4f37-a56e-68bd00ce4560/deploy\
        \ \\\n  -H \"Authorization: Bearer ${{ needs.get-token.outputs.access_token\
        \ }}\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n        \"\
        source\": \"github\",\n        \"branch\": \"main\"\n      }'\n"
  deploy-to-test:
    name: Copiar contenido de Dev a Test
    runs-on: ubuntu-latest
    needs: sync-from-github
    steps:
    - name: Llamar a la API de Fabric para copiar contenido
      run: "curl -X POST https://api.fabric.microsoft.com/v1/workspaces/3852a0cf-16cb-4f37-a56e-68bd00ce4560/copyToWorkspace\
        \ \\\n  -H \"Authorization: Bearer ${{ needs.get-token.outputs.access_token\
        \ }}\" \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n        \"\
        targetWorkspaceId\": \"b0893134-54da-413c-96c7-cf109f8a1fb3\",\n        \"\
        overwrite\": true\n      }'\n"
  deploy-stage-content:
    name: Desplegar contenido desde Dev a Test usando Deploy Stage Content
    runs-on: ubuntu-latest
    needs: sync-from-github
    steps:
    - name: Llamar a la API oficial de Fabric para desplegar etapa
      run: "\n              curl -X POST https://api.fabric.microsoft.com/v1/deploymentPipelines/github-integration-pipelines/stages/3852a0cf-16cb-4f37-a56e-68bd00ce4560/deploy\
        \                 -H \"Authorization: Bearer ${{ needs.get-token.outputs.access_token\
        \ }}\"                 -H \"Content-Type: application/json\"\n            "
