name: Fabric Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  get-token:
    name: Obtener token de Azure AD
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.get_token.outputs.access_token }}
    steps:
      - name: Obtener token con client_credentials
        id: get_token
        run: |
          response=$(curl -X POST https://login.microsoftonline.com/${{ secrets.TENANT_ID }}/oauth2/v2.0/token \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "client_id=${{ secrets.CLIENT_ID }}&scope=https%3A%2F%2Fapi.fabric.microsoft.com%2F.default&client_secret=${{ secrets.CLIENT_SECRET }}&grant_type=client_credentials")
          echo "access_token=$(echo $response | jq -r .access_token)" >> $GITHUB_OUTPUT

  sync-from-github:
    name: Sincronizar contenido desde GitHub a Dev
    runs-on: ubuntu-latest
    needs: get-token
    steps:
      - name: Llamar a la API de Fabric para sincronizar contenido
        run: |
          curl -X POST https://api.fabric.microsoft.com/v1/workspaces/3852a0cf-16cb-4f37-a56e-68bd00ce4560/deploy \
            -H "Authorization: Bearer ${{ needs.get-token.outputs.access_token }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "source": "github",
                  "branch": "main"
                }'

  deploy-to-test:
    name: Copiar contenido de Dev a Test
    runs-on: ubuntu-latest
    needs: sync-from-github
    steps:
      - name: Llamar a la API de Fabric para copiar contenido
        run: |
          response=$(curl -s -w "%{http_code}" -o response.json -X POST https://api.fabric.microsoft.com/v1/workspaces/3852a0cf-16cb-4f37-a56e-68bd00ce4560/copyToWorkspace \
            -H "Authorization: Bearer ${{ needs.get-token.outputs.access_token }}" \
            -H "Content-Type: application/json" \
            -d '{
                  "targetWorkspaceId": "b0893134-54da-413c-96c7-cf109f8a1fb3",
                  "overwrite": true
                }')
          echo "Código HTTP: $response"
          cat response.json
